### ISSUE TITLE
Combining different models 

### ISSUE THREAD

**Issue by kadir-gunel** [amunmt/amunmt#64]
Is it possible to create combination of different models ? Say, I have created n different models with different settings and I want to take the average of them and do the translation?  

B.R.

**Comment by tomekd** [comment]
Hi,
yes, it is. The only condition to meet is having the same target vocabulary.

**Comment by emjotde** [comment]
Hi,
What exactly do you mean by "different settings"?

**Comment by kadir-gunel** [comment]
Hi @emjotde ,

Actually 2 things : 
1 . I have exact the same model (depth of enc/dec, embeddings layers, etc. are all the same) , trained with the same data set **but with different settings** (one of them is preprocessed by bpe and the other is preprocessed by some other technique.) 

2.  I have 2 different models (the depth of enc/dec, embedding layers are different) again trained by the same data set with different settings (as described above).

**Comment by emjotde** [comment]
Hi, 

the different preprocessing makes that difficult. In the least you would have to have consistent preprocessing of the target, otherwise the decoder has no idea how to handle this. 

Amun can ensemble different models as long as the vocabularies match, but Amun handles only one model type, the vanilla dl4mt/nematus model. 

At the moment I am working on ensembling different model types (different architectures, e.g. different layers), but this would again require matching vocabularies and tokenization etc. I see no good way of doing this correctly with different preprocessing settings. Far too messy.

**Comment by kadir-gunel** [comment]
I am sorry, I am a little confused. Do you mean, right now, for the dl4mt/nematus model with different layer sizes, it is possible to combine different models. Is it correct ? (Assuming, the voc. and preprocessing steps are the same)

**Comment by emjotde** [comment]
Sorry, let me clarify:

* Different number of neurons in the same layers: yes
* Different numbers of layers: not yet.

**Comment by kadir-gunel** [comment]
Thank you 👍
